// *** REGISTER ACTION *** //

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

// *** LOGIN ACTION ***//

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// *** RECIPES ***//

export const FETCH_DINOS_START = "FETCH_DINOS_START";
export const FETCH_DINOS_SUCCESS = "FETCH_DINOS_SUCCESS";
export const FETCH_DINOS_FAILURE = "FETCH_DINOS_FAILURE";

export const ADD_DINOS_START = "ADD_DINOS_START";
export const ADD_DINOS_SUCCESS = "ADD_DINOS_SUCCESS";
export const ADD_DINOS_FAILURE = "ADD_DINOS_FAILURE";

//  *** GET RECIPE BY USER *** //

export const FETCH_DINOSBYUSER_START = "FETCH_DINOSBYUSER_START";
export const FETCH_DINOSBYUSER_SUCCESS = "FETCH_DINOSBYUSER_SUCCESS";
export const FETCH_DINOSBYUSER_FAILURE = "FETCH_DINOSBYUSER_FAILURE";

// *** UPDATE AND DELETE ACTIONS *** //

export const DELETE_DINOS_START = "DELETE_DINOS_START";
export const DELETE_DINOS_SUCCESS = "DELETE_DINOS_SUCCESS";
export const DELETE_DINOS_FAILURE = "DELETE_DINOS_FAILURE";

export const UPDATE_DINOS_START = "UPDATE_DINOS_START";
export const UPDATE_DINOS_SUCCESS = "UPDATE_DINOS_SUCCESS";
export const UPDATE_DINOS_FAILURE = "UPDATE_DINOS_FAILURE";
